src/config/routes.rb
Rails.application.routes.draw do
  get  'signup' => 'sessions#new', as: :signup
  post 'signup' => 'sessions#save', as: :signup_save
  get  'login' => 'sessions#create', as: :login
  post 'login' => 'sessions#create_post'
  get  'logout' => 'sessions#destroy', as: :logout

  get   'accounts/details'
  match 'accounts/details_post', via: [:post, :patch]
  get   'accounts/password'
  match 'accounts/password_post', via: [:post, :patch]
  match 'accounts/notifications_post', via: [:post, :patch]
  match 'accounts/settings_post', via: [:post, :patch]
  get   'accounts/resend_activation'

  # account activation urls
  get  'activate' => 'sessions#activate_start', as: :activate_start
  post 'activate' => 'sessions#activate_start_post', as: :activate_start_post
  get  'activate/:key' => 'sessions#activate', as: :activate

  # password recovery urls
  get  'recover' => 'sessions#recover_start', as: :recover_start
  post 'recover' => 'sessions#recover_start_post', as: :recover_start_post
  get  'recover/:key' => 'sessions#recover', as: :recover

  resources :portfolios
  resources :portfolio_changes
  resources :asset_categories

  root 'site#index'
end

src/app/models/account.rb
class Account < ApplicationRecord

  has_secure_password
  belongs_to   :currency

  before_save      :downcase_email
  after_initialize :init_account, if: :new_record?

  validates :email,
              presence: true,
              uniqueness: true,
              format: {
                  with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
              }
  validates :currency_id, presence: true

  STATUS_INACTIVE = 0
  STATUS_ACTIVE   = 1

  DUMMY_PASSWORD  = 'account without password'
  KEY_EXPIRY_DAYS = 1

  def to_s
    self.name.blank? ? self.email : self.name
  end

  def params_name
    self.class.name.downcase.singularize
  end

  def gravatar_url(size = 200)
    "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(downcase_email)}?d=mm&s=#{size}"
  end

  def no_password?
    self.password_digest == Account::DUMMY_PASSWORD
  end

  def inactive?
    self.status == Account::STATUS_INACTIVE
  end

  def not_activated?
    self.inactive? || self.no_password?
  end

  def active?
    self.status == Account::STATUS_ACTIVE
  end

  def set_inactive!
    self.status = Account::STATUS_INACTIVE
    self.save
  end

  def set_active!
    self.status = Account::STATUS_ACTIVE
    # need to invalidate the previous key
    self.generate_activation_key
    self.save
  end

  def activation_key_valid?(key)
    self.activation_key == key && self.activation_expiry >= DateTime.now ?
        true :
        false
  end

  def generate_activation_key
    self.activation_key    = SecureRandom.urlsafe_base64(64)
    self.activation_expiry = (DateTime.now + KEY_EXPIRY_DAYS.days).strftime('%Y-%m-%d %H:%M:%S')
  end

  def generate_activation_key!
    generate_activation_key
    self.save
  end

  private
  def init_account
    self.currency_id = Currency::DEFAULT_CURRENCY_ID
    self.password_digest = Account::DUMMY_PASSWORD
    self.generate_activation_key
  end

  def downcase_email
    self.email = email.downcase if email.present?
  end
end

src/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_action :authorize
  before_action :load_account

  def details
    self.page_title = 'Account Details'
    @asset_types = AssetType.all
  end

  def details_post
    @account.attributes = account_params()
    save_and_redirect 'Profile updated successfully.'
  end

  def password_post
    @account.attributes = password_params()
    save_and_redirect 'Password changed successfully.'
  end

  def notifications_post
  end

  def settings_post
    @account.attributes = settings_params()
    update_asset_categories
    save_and_redirect 'Settings changed successfully.'
  end

  def resend_activation
    if @account.not_activated?
      @account.generate_activation_key!
      AccountMailer.activation_email(@account).deliver_now
      redirect_to root_url, flash: { success: 'Activation email has been sent.' }
    else
      redirect_to root_url
    end
  end

  private
  def update_asset_categories

  end

  def save_and_redirect(message)
    if @account.save
      redirect_to({ action: 'details' }, flash: { success: message })
    else
      redirect_to({ action: 'details' }, flash: { danger: @account.errors.full_messages.join('<br/>') })
    end
  end

  def password_params()
    params.require(@account.params_name).permit(:password)
  end

  def account_params()
    params.require(@account.params_name).permit(:name, :email)
  end

  def settings_params()
    params.require(@account.params_name).permit(:currency_id)
  end
end

src/app/helpers/accounts_helper.rb
module AccountsHelper
end

src/app/views/accounts/_notifications.html.erb
<div class="row">
  <div class="col-sm-4 col-sm-push-4">
    <div class="panel panel-info" id="notification-settings">
      <div class="panel-heading">
        <h4 class="panel-title"><i class="fa fa-bell"></i> Notifications</h4>
      </div>

      <div class="panel-body">
        <%= form_for(@account, url: { action: 'notifications_post'}) do |f| %>
          <p class="text-muted">No settings yet</p>

          <div class="text-right">
            <button class="btn btn-default form-cancel">Cancel</button>
            <button type="submit" class="btn btn-primary" disabled>Save</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

src/app/views/accounts/_password.html.erb
<div class="row">
  <div class="col-sm-4 col-sm-push-4">
    <div class="panel panel-info" id="change-password"<%= local_assigns.has_key?(:show) ? ' style="display:block"'.html_safe : '' %>>
      <div class="panel-heading">
        <h4 class="panel-title"><i class="fa fa-lock"></i> <%= @account.no_password? ? 'Set' : 'Change' %> Password</h4>
      </div>

      <div class="panel-body">
        <%= form_for(@account, url: { action: 'password_post'}) do |f| %>
          <div class="form-group">
            <label for="account_password">Your new password</label>
            <%= f.password_field :password, class: 'form-control', data: { :toggle => 'password' } %>
          </div>

          <div class="text-right">
            <button class="btn btn-default form-cancel">Cancel</button>
            <button type="submit" class="btn btn-primary"><%= @account.no_password? ? 'Set' : 'Change' %> password</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

src/app/views/accounts/_settings.html.erb
<div class="row">
  <div class="col-sm-4 col-sm-push-4">
    <div class="panel panel-info" id="general-settings">
      <div class="panel-heading">
        <h4 class="panel-title"><i class="fa fa-cog"></i> Settings</h4>
      </div>

      <div class="panel-body">
        <%= form_for(@account, url: { action: 'settings_post'}) do |f| %>
          <div class="form-group">
            <label for="account_password">Your main currency</label>
            <%= f.collection_select :currency_id, Currency.all, :id, :full_name, { prompt: true }, { :class => 'form-control' } %>
          </div>

          <div class="form-group">
            <label for="account_password">Custom Asset Categories</label>
            <%= hidden_field_tag 'category_url', new_asset_category_path %>
            <div class="row">
              <% @asset_types.each do |at| %>
              <div class="col-lg-6">
                <div class="list-group">
                  <div class="list-group-item active">
                    <h4 class="list-group-item-heading"><%= at.name %></h4>
                  </div>
                  <% at.asset_categories.each do |ac| %>
                  <div class="list-group-item">
                    <%= ac.name %>
                    <% if ac.account_id.present? %>
                    <%= hidden_field_tag "asset_category_#{at.id}[]", ac.name, { :class => 'ac-name' } %>
                    <a href="#" class="pull-right remove-item"><i class="fa fa-minus"></i></a>
                    <% end %>
                  </div>
                  <% end %>
                  <div class="list-group-item template">
                    <span></span>
                    <%= hidden_field_tag "asset_category_#{at.id}[]", '', { :class => 'ac-name' } %>
                    <a href="#" class="pull-right remove-item" title="Remove"><i class="fa fa-minus"></i></a>
                  </div>
                  <div class="list-group-item add-new">
                    <div class="input-group">
                      <input type="text" class="form-control item-name" placeholder="Provide name" />
                      <a href="#" class="input-group-addon btn btn-success confirm-add">
                        <i class="fa fa-check"></i>
                      </a>
                    </div>
                  </div>
                  <a class="list-group-item list-group-item-success new-item">
                    Add new...
                    <i class="fa fa-plus pull-right"></i>
                  </a>
                </div>
              </div>
              <% end %>
            </div>
            <% #f.collection_select :currency_id, Currency.all, :id, :full_name, { prompt: true }, { :class => 'form-control' } %>
          </div>

          <div class="text-right">
            <button class="btn btn-default form-cancel">Cancel</button>
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

src/app/views/accounts/details.html.erb
<div class="row">
  <div class="col-sm-4 col-sm-push-4">
    <div class="panel panel-default" id="account-details">
      <div class="panel-body">
        <div class="text-center">
          <%= image_tag(@account.gravatar_url, class: 'img-circle', alt: @account) %>
        </div>
        <div class="account-summary text-center">
          <a href="#" class="edit"><i class="fa fa-edit"></i></a>
          <% if @account.name.present? %>
          <h3><%= @account.name %></h3>
          <% end %>
          <p class="lead">
            <i class="fa fa-envelope"></i> <%= @account.email %>
          </p>
        </div>
        <%= form_for(@account, url: { action: 'details_post' }) do |f| %>
          <div class="form-group">
            <label for="account_name">Name</label>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <label for="account_email">Email</label>
            <%= f.text_field :email, class: 'form-control' %>
          </div>

          <div class="text-right">
            <button class="btn btn-default form-cancel">Cancel</button>
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<h4 class="text-center settings-link">
  <a href="#" class="text-size-large">Change general settings</a>
</h4>
<%= render 'settings' %>

<h4 class="text-center notifications-link">
  <a href="#" class="text-size-large">Change notifications settings</a>
</h4>
<%= render 'notifications' %>

<h4 class="text-center password-link">
  <a href="#" class="text-size-large"><%= @account.no_password? ? 'Set' : 'Change' %> password</a>
</h4>
<%= render 'password' %>

src/app/views/accounts/password.html.erb
<%= render 'password', { :show => true } %>